name: Build executables for Windows
on:
  push:
    branches: [ master, develop, build ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Build vvenc
      shell: cmd
      run: |
        make install-release

    - name: Run tests
      shell: cmd
      run: |
        bin/release-static/vvenclibtest.exe

    - name: Upload standalone executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: vvenc_win64
        path: |
          bin/release-static/vvencapp.exe
          bin/release-static/vvencFFapp.exe
          LICENSE.txt